name: test
on:
  push
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "attach head"
        run: git checkout "${GITHUB_REF#refs/heads/}"

      - name: "setup JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "get generic info"
        uses: ModelingValueGroup/generic-info@master

      - name: "get buildTools"
        uses: ModelingValueGroup/buildTools@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "(re)generate some files"
        run:  |
          . <(java -jar buildTools.jar)
          correctEols
          correctHeaders header

      - name: "test"
        run: |
          set -euo pipefail
          . functions.sh  1>&2
          echo "#dry" > dry.jar
          echo "#dry" > dry-sources.jar
          echo "#dry" > dry-javadoc.jar

          out="$(DRY=echo main "${{ secrets.GITHUB_TOKEN }}" dry.jar "mygroup:myartifact:0.0:jar" "")"
          exp="mvn -B -s settings.xml deploy:deploy-file -DgroupId=mygroup -DartifactId=myartifact -Dversion=0.0 -Dpackaging=jar -DrepositoryId=github -Durl=https://maven.pkg.github.com/ModelingValueGroup/upload-maven-package-action -Dfile=dry.jar -Dsources=dry-sources.jar -Djavadoc=dry-javadoc.jar"

          if [[ "$out" != "$exp" ]]; then
            echo "::error::test failed"
            echo "::error::    expected: $exp"
            echo "::error::    output  : $out"
            exit 44
          fi
          rm dry.jar dry-sources.jar dry-javadoc.jar
          echo "all ok"

      - name: "push changes back to github"
        run:  |
          . <(java -jar buildTools.jar)
          pushBackToGithub "${{ secrets.GITHUB_TOKEN }}" "automation@modelingvalue.com" "adjusted files [by github actions]"
