name: test
on:
  push
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "install packages"
        run: |
          sudo apt-get install -y \
            bash \
            xmlstarlet \
            jq \
            maven

      - name: "test"
        run: |
          set -euo pipefail
          . functions.sh  1>&2
          echo "#dry" > dry.pack
          out="$(DRY=echo main \
            "${{ secrets.GITHUB_TOKEN }}" \
            "dry.pack" \
            "mygroup:myartifact:0.0:pack" \
            "")"
          exp="mvn -B -s settings.xml deploy:deploy-file -DgroupId=mygroup -DartifactId=myartifact -Dversion=0.0 -Dpackaging=pack -DrepositoryId=github -Dfile=dry.pack -DpomFile= -Durl=https://maven.pkg.github.com/ModelingValueGroup/upload-maven-package-action"
          if [[ "$out" != "$exp" ]]; then
            echo "::error::test failed"
            echo "::error::    expected: $exp"
            echo "::error::    output  : $out"
            exit 44
          fi
