name: test
on:
  push
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "install packages"
        run: |
          sudo apt-get install -y \
            bash \
            xmlstarlet \
            jq \
            maven

      - name: "test"
        run: |
          set -euo pipefail
          . functions.sh  1>&2
          echo "#dry" > dry.sh
          out="$(DRY=echo main \
            "ModelingValueGroup/buildTools" \
            "${{ secrets.GITHUB_TOKEN }}" \
            "dry.sh" \
            "com.modelingvalue:buildTools:0.0:sh" \
            "")"
          exp="mvn -B -s settings.xml deploy:deploy-file -DgroupId=com.modelingvalue -DartifactId=buildTools -Dversion=0.0 -Dpackaging=sh -DrepositoryId=github -Dfile=dry.sh -DpomFile= -Durl=https://maven.pkg.github.com/ModelingValueGroup/buildTools"
          if [[ "$out" != "$exp" ]]; then
            echo "::error::test failed"
            echo "::error::    expected: $exp"
            echo "::error::    output  : $out"
            exit 44
          fi
