name: test
on:
  push
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: test
        run: |
          sudo apt-get install -y \
            bash \
            xmlstarlet \
            jq \
            maven
          . functions.sh  1>&2
          exp="mvn -B -s settings.xml deploy:deploy-file -DgroupId=aa -DartifactId=bb -Dversion=md -Dpackaging=1.0 -DrepositoryId=github -Dfile=README.md -DpomFile= -Durl=https://maven.pkg.github.com/ModelingValueGroup/upload-maven-package-action"
          out="$(DRY=echo main \
            "$GITHUB_REPOSITORY" \
            "${{ secrets.GITHUB_TOKEN }}" \
            "README.md" \
            "aa:bb:md:1.0" \
            "")"
          if [[ "$out" != "$exp" ]]; then
            echo "::error::test failed"
            echo "::error::    expected: $exp"
            echo "::error::    output  : $out"
            exit 44
          fi
