name: test
on:
  push
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: test
        run: |
          set 1>&2
          export DRY=echo
          . functions.sh  1>&2
          main \
            "$GITHUB_REPOSITORY" \
            "${{ secrets.GITHUB_TOKEN }}" \
            "README.md" \
            "aa:bb:md:1.0" \
            "noPom"
