name: test
on:
  push
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "attach head"
        run: git checkout "${GITHUB_REF#refs/heads/}"

      - name: "setup JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "get generic info"
        uses: ModelingValueGroup/generic-info@master

      - name: "get buildtools"
        uses: ModelingValueGroup/buildtools@master

      - name: "(re)generate some files"
        run:  |
          . <(java -jar ~/buildtools.jar)
          correctEols
          correctHeaders header

      - name: "push changes back to github"
        run: |
          . <(java -jar ~/buildtools.jar)
          pushBackToGithub "${{ secrets.GITHUB_TOKEN }}" "automation@modelingvalue.com" "adjusted files [by github actions]"

      - name: "test"
        run: |
          set -euo pipefail
          . <(java -jar ~/buildtools.jar)
          . functions.sh  1>&2
          runUploadArtifactTest "tmp.modelingvalue" "upload-maven-package-action-test" "${{ secrets.REPO_AND_PACKAGES_TOKEN }}"
          echo "all ok"
