name: test
on:
  push
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "attach head"
        run: git checkout "${GITHUB_REF#refs/heads/}"

      - name: "setup JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "get generic info"
        uses: ModelingValueGroup/generic-info@master

      - name: "get buildTools"
        uses: ModelingValueGroup/buildTools@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "(re)generate some files"
        run:  |
          . <(java -jar buildTools.jar)
          correctEols
          correctHeaders header

      - name: "test"
        run: |
          set -euo pipefail
          . functions.sh  1>&2
          echo "#dry" > dry.pack
          echo "#dry" > dry-javadoc.pack
          mapfile -t out < <(DRY=echo main "${{ secrets.GITHUB_TOKEN }}" "dry.pack" "mygroup:myartifact:0.0:pack" "")
          exp=(
            "mvn -B -s settings.xml deploy:deploy-file -DgroupId=mygroup -DartifactId=myartifact -Dversion=0.0 -Dpackaging=pack -DrepositoryId=github -Dfile=dry.pack -DpomFile= -Durl=https://maven.pkg.github.com/ModelingValueGroup/upload-maven-package-action"
            "mvn -B -s settings.xml deploy:deploy-file -DgroupId=mygroup -DartifactId=myartifact-javadoc -Dversion=0.0 -Dpackaging=pack -DrepositoryId=github -Dfile=dry-javadoc.pack -DpomFile= -Durl=https://maven.pkg.github.com/ModelingValueGroup/upload-maven-package-action"
          )
          for i in 0 1; do
            if [[ "${out[$i]}" == "${exp[$i]}" ]]; then
              echo "... line $i: ok"
            else
              echo "::error::test failed"
              echo "::error::    expected: ${exp[$i]}"
              echo "::error::    output  : ${out[$i]}"
              exit 44
            fi
          done
          rm dry.pack
          echo "all ok"

      - name: "push changes back to github"
        run:  |
          . <(java -jar buildTools.jar)
          pushBackToGithub "${{ secrets.GITHUB_TOKEN }}" "automation@modelingvalue.com" "adjusted files [by github actions]"
